2022-12-27 09:07:56,514 [ERROR] django.request: Internal Server Error: /api/training/start
Traceback (most recent call last):
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/tensor/anaconda3/envs/chat_service/auto_classify/wv_app/views.py", line 21, in post
    result_dic = start_learning.delay(data)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/home/tensor/anaconda3/envs/chat_service/lib/python3.8/site-packages/celery/app/task.py", line 540, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: start_learning() takes 1 positional argument but 2 were given
2022-12-27 09:08:16,758 [INFO] django.utils.autoreload: /home/tensor/anaconda3/envs/chat_service/auto_classify/wv_app/tasks.py changed, reloading.
2022-12-27 09:08:20,764 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2022-12-27 09:09:24,906 [INFO] my: task kill
2022-12-27 09:09:30,487 [INFO] my: task kill
